accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register')
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_room/', views.create_room, name='create_room'),
    path('my_rooms/', views.rooms_list, name='rooms_list'),
    path('<str:room_name>/', views.room, name='room'),
]

django_chat/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('', include('chat.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.conf import settings
import uuid


class ChatRoom(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_rooms')
    uuid = models.UUIDField(editable=False, default=uuid.uuid4, unique=True)
    name = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords does not match')
        return cd['password2']

chat/forms.py
from .models import ChatRoom
from django.forms import ModelForm, forms, CharField, PasswordInput


class JoinChatRoomForm(forms.Form):
    name = CharField()
    password = CharField(widget=PasswordInput)


class CreateChatRoomForm(ModelForm):
    class Meta:
        model = ChatRoom
        fields = ['name', 'password']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserRegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return redirect('chat:index')
    else:
        user_form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'user_form': user_form})

chat/views.py
from django.shortcuts import render, redirect
from .models import ChatRoom
from .forms import JoinChatRoomForm, CreateChatRoomForm
from django.contrib.auth.decorators import login_required
from agora_token_builder import RtcTokenBuilder
import random
import time
import os


def index(request):
    if request.method == 'POST':
        form = JoinChatRoomForm(request.POST)
        chat_room = ChatRoom.objects.filter(name=form.data['name'])
        if form.is_valid() and chat_room.exists() and form.data['password'] == chat_room[0].password:
            request.session['room'] = form.data['name']
            return redirect('chat:room', room_name=form.data['name'])
        else:
            form = JoinChatRoomForm()
    else:
        form = JoinChatRoomForm()
    return render(request, 'chat/index.html', {'form': form})


@login_required
def create_room(request):
    if request.method == 'POST':
        form = CreateChatRoomForm(request.POST)
        if form.is_valid():
            new_room = form.save(commit=False)
            new_room.user = request.user
            new_room.save()
            return redirect('chat:index')
    else:
        form = CreateChatRoomForm()
    return render(request, 'chat/create_room.html', {'form': form})


def room(request, room_name):
    if 'room' in request.session and request.session['room'] == room_name:

        # building agora token
        app_id = str(os.getenv('APP_ID'))
        app_cert = str(os.getenv('APP_CERT'))
        channel = room_name
        uid = random.randint(1, 200)
        expiration = 3600 * 24
        current_time = time.time()
        privilege_expired_ts = current_time + expiration
        role = 1

        token = RtcTokenBuilder.buildTokenWithUid(app_id, app_cert, channel, uid, role, privilege_expired_ts)

        return render(request, 'chat/room.html', {'room_name': room_name, 'token': token, 'uid': uid, 'app_id': app_id})
    else:
        return redirect('chat:index')


@login_required
def rooms_list(request):
    rooms = ChatRoom.objects.filter(user=request.user)
    return render(request, 'chat/rooms_list.html', {'rooms': rooms})

accounts/templates/accounts/register.html
{% extends "auth_layout.html" %}

{% block content %}
    <header>
        <div class="header-text">
            <h1>Register</h1>
            <p>If you already have an account, <a href="{% url 'accounts:login' %}">you can login here</a></p>
        </div>
    </header>

    <form action="." method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <p><input type="submit" value="Create an account" class="submit-button"></p>
    </form>
{% endblock %}

accounts/templates/auth_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Titleeeeee</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</head>
<body>

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">DjangoChat</a>
        <div class="d-flex">
            <span class="nav-link time">{%  now  'l, d.m.o' %}</span>
            <a class="nav-link link home" href="{% url 'chat:index' %}">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-link link" href="{% url 'chat:rooms_list' %}">My rooms</a><br>
                <a class="nav-link link" href="{% url 'accounts:logout' %}">Logout</a><br>
            {% else %}
                <a class="nav-link link" href="{% url 'accounts:login' %}">Login</a><br>
            {% endif %}
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<style>
    .container-fluid{
        margin-left: 150px;
        margin-right: 150px;
    }


    .time{
        color: black;
    }
    .time:hover{
        color: black;
    }

    .link{
        transition: .2s;

    }
    .link:hover{
        font-weight: bold;
    }
</style>
</body>
</html>

chat/templates/chat/create_room.html
{% extends 'chat/base.html' %}

{% block content %}

    <div class="content">
        <h2>Create new chat room:</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <p class="form-label">{{ form.name.label }}:</p>
                <p>{{ form.name }}</p>
            </div>
            <div class="mb-3">
                <p class="form-label">{{ form.password.label }}:</p>
                <p>{{ form.password }}</p>
            </div>
            <div class="mb-3">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </form>
        <h3>or <a href="{% url 'chat:index' %}">go back</a></h3>
    </div>

<style>

    .content{
        position: absolute;
        width: 40%;
        top: 20%;
        right: 30%;
        display: flex;
        flex-direction: column;
    }

    .content form{
        width: 100%;
        align-self: center;
        padding: 30px;
    }

    .content form input[type=text], input[type=password]{
        width: 90%;
    }

    .content form input[type=submit]{
        margin-top: 20px;
    }
</style>

{% endblock %}

chat/templates/chat/index.html
{% extends 'chat/base.html' %}

{% block content %}

    <div class="content">
        <h2>You can join an existing room:</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <p class="form-label">{{ form.name.label }}:</p>
                <p>{{ form.name }}</p>
            </div>
            <div class="mb-3">
                <p class="form-label">{{ form.password.label }}:</p>
                <p>{{ form.password }}</p>
            </div>
            <div class="mb-3">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </form>
        {% if user.is_authenticated %}
            <h3>or <a href="{% url 'chat:create_room' %}">create a new room</a></h3>
        {% else %}
            <h3>or <a href="{% url 'accounts:login' %}">log in</a> to create a new room</h3>
        {% endif %}
    </div>


<style>

    .content{
        position: absolute;
        top: 30%;
        left: 5%;
        display: flex;
        flex-direction: column;
    }

    .content form{
        width: 100%;
        align-self: center;
        padding: 30px;
    }

        .content form input[type=text], input[type=password]{
        width: 90%;
    }

</style>

{% endblock %}

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ room_name }}</title>
    <script src="https://kit.fontawesome.com/49b5438e0f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/room.css' %}">
</head>
<body>
{{ room_name|json_script:"room-name" }}
{{ token|json_script:"token" }}
{{ uid|json_script:"uid" }}
{{ app_id|json_script:"app_id" }}

<h2>{{ room_name }}</h2>

<div class="video-chat">

    <div class="video-controls">
        <div class="icon" id="leave-btn" >
            <i class="fas fa-times-circle"></i>
        </div>
        <div class="icon" id="microphone-btn" >
            <i class="fas fa-microphone"></i>
        </div>
        <div class="icon" id="camera-btn">
            <i class="fas fa-camera"></i>
        </div>
    </div>
</div>


<div class="chat">
    <div class="chatbox">

    </div>
    <div class="controls">
        <input id="chat-message-input" type="text">
        <input id="chat-message-submit" type="button" value="Send">
    </div>
    <p class="error"></p>
</div>


<script type="text/javascript" src="{% static 'js/AgoraRTC_N-4.11.0.js' %}"></script>
<script type="text/javascript" src="{% static 'js/room.js' %}"></script>
</body>
</html>

chat/templates/chat/rooms_list.html
{% extends 'chat/base.html' %}


{% block content %}
    <table class="table">
        <tr>
            <th scope="col">name</th>
            <th scope="col">password</th>
        </tr>
        {% for room in rooms %}
            <tr>
                <td class="td-name">{{ room.name }}</td>
                <td><span id="password-{{ room.uuid }}"></span><span id="show-{{ room.uuid }}" class="show">show password</span></td>
            </tr>
        {% endfor %}
    </table>



<style>
    .table{
        position: absolute;
        width: 50%;
        top: 15%;
        right: 30%;
    }
    .show{
        cursor: pointer;
        text-decoration: underline;
    }
</style>

<script>
     {% for room in rooms %}
        document.querySelector('#show-{{ room.uuid }}').addEventListener('click', function (){
            let password = document.querySelector('#password-{{ room.uuid }}');
            let showPassword = document.querySelector('#show-{{ room.uuid }}');

            if (password.innerText === ''){
                password.textContent = '{{ room.password }} \u00A0\u00A0\ ';
                showPassword.textContent = 'hide';
            } else {
                password.textContent = '';
                showPassword.textContent = 'show password';
            }

        })
    {% endfor %}
</script>
{% endblock %}